# Don't use tabs, only spaces.  YAML will yell.


# admin = Admin of the full website
# member = either a team coach or player
user_type:
    #- player
    #- coach
    - admin
    - member

visibility:
    - private
    - coach
    - player
    - public
