User.create("first_name"=>"John", "last_name"=>"Doe", "user_type"=>"member")
Team.create("name"=>"Tigers", "mascot"=>"Tiger")
Team.create("name"=>"Sharks", "mascot"=>"Goldfish")
Position.create("title"=>"Goalkeeper")
Position.create("title"=>"Defender")
Position.create("title"=>"Mid-Fielder")
Position.create("title"=>"Forward")
TeamMember.create("team_id"=>1, "user_id"=>1, "is_coach"=>nil)
TeamMember.create("team_id"=>2, "user_id"=>1, "is_coach"=>nil)
PlayerPosition.create("team_member_id"=>1, "position_id"=>1)
PlayerPosition.create("team_member_id"=>1, "position_id"=>2)
