require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeamPlayersController do

  # This should return the minimal set of attributes required to create a valid
  # TeamPlayer. As you add validations to TeamPlayer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeamPlayersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all team_players as @team_players" do
      team_player = TeamPlayer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:team_players).should eq([team_player])
    end
  end

  describe "GET show" do
    it "assigns the requested team_player as @team_player" do
      team_player = TeamPlayer.create! valid_attributes
      get :show, {:id => team_player.to_param}, valid_session
      assigns(:team_player).should eq(team_player)
    end
  end

  describe "GET new" do
    it "assigns a new team_player as @team_player" do
      get :new, {}, valid_session
      assigns(:team_player).should be_a_new(TeamPlayer)
    end
  end

  describe "GET edit" do
    it "assigns the requested team_player as @team_player" do
      team_player = TeamPlayer.create! valid_attributes
      get :edit, {:id => team_player.to_param}, valid_session
      assigns(:team_player).should eq(team_player)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TeamPlayer" do
        expect {
          post :create, {:team_player => valid_attributes}, valid_session
        }.to change(TeamPlayer, :count).by(1)
      end

      it "assigns a newly created team_player as @team_player" do
        post :create, {:team_player => valid_attributes}, valid_session
        assigns(:team_player).should be_a(TeamPlayer)
        assigns(:team_player).should be_persisted
      end

      it "redirects to the created team_player" do
        post :create, {:team_player => valid_attributes}, valid_session
        response.should redirect_to(TeamPlayer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved team_player as @team_player" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeamPlayer.any_instance.stub(:save).and_return(false)
        post :create, {:team_player => {  }}, valid_session
        assigns(:team_player).should be_a_new(TeamPlayer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeamPlayer.any_instance.stub(:save).and_return(false)
        post :create, {:team_player => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested team_player" do
        team_player = TeamPlayer.create! valid_attributes
        # Assuming there are no other team_players in the database, this
        # specifies that the TeamPlayer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TeamPlayer.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => team_player.to_param, :team_player => { "these" => "params" }}, valid_session
      end

      it "assigns the requested team_player as @team_player" do
        team_player = TeamPlayer.create! valid_attributes
        put :update, {:id => team_player.to_param, :team_player => valid_attributes}, valid_session
        assigns(:team_player).should eq(team_player)
      end

      it "redirects to the team_player" do
        team_player = TeamPlayer.create! valid_attributes
        put :update, {:id => team_player.to_param, :team_player => valid_attributes}, valid_session
        response.should redirect_to(team_player)
      end
    end

    describe "with invalid params" do
      it "assigns the team_player as @team_player" do
        team_player = TeamPlayer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeamPlayer.any_instance.stub(:save).and_return(false)
        put :update, {:id => team_player.to_param, :team_player => {  }}, valid_session
        assigns(:team_player).should eq(team_player)
      end

      it "re-renders the 'edit' template" do
        team_player = TeamPlayer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeamPlayer.any_instance.stub(:save).and_return(false)
        put :update, {:id => team_player.to_param, :team_player => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested team_player" do
      team_player = TeamPlayer.create! valid_attributes
      expect {
        delete :destroy, {:id => team_player.to_param}, valid_session
      }.to change(TeamPlayer, :count).by(-1)
    end

    it "redirects to the team_players list" do
      team_player = TeamPlayer.create! valid_attributes
      delete :destroy, {:id => team_player.to_param}, valid_session
      response.should redirect_to(team_players_url)
    end
  end

end
