require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TeamImagesController do

  # This should return the minimal set of attributes required to create a valid
  # TeamImage. As you add validations to TeamImage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TeamImagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all team_images as @team_images" do
      team_image = TeamImage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:team_images).should eq([team_image])
    end
  end

  describe "GET show" do
    it "assigns the requested team_image as @team_image" do
      team_image = TeamImage.create! valid_attributes
      get :show, {:id => team_image.to_param}, valid_session
      assigns(:team_image).should eq(team_image)
    end
  end

  describe "GET new" do
    it "assigns a new team_image as @team_image" do
      get :new, {}, valid_session
      assigns(:team_image).should be_a_new(TeamImage)
    end
  end

  describe "GET edit" do
    it "assigns the requested team_image as @team_image" do
      team_image = TeamImage.create! valid_attributes
      get :edit, {:id => team_image.to_param}, valid_session
      assigns(:team_image).should eq(team_image)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TeamImage" do
        expect {
          post :create, {:team_image => valid_attributes}, valid_session
        }.to change(TeamImage, :count).by(1)
      end

      it "assigns a newly created team_image as @team_image" do
        post :create, {:team_image => valid_attributes}, valid_session
        assigns(:team_image).should be_a(TeamImage)
        assigns(:team_image).should be_persisted
      end

      it "redirects to the created team_image" do
        post :create, {:team_image => valid_attributes}, valid_session
        response.should redirect_to(TeamImage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved team_image as @team_image" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeamImage.any_instance.stub(:save).and_return(false)
        post :create, {:team_image => {  }}, valid_session
        assigns(:team_image).should be_a_new(TeamImage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TeamImage.any_instance.stub(:save).and_return(false)
        post :create, {:team_image => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested team_image" do
        team_image = TeamImage.create! valid_attributes
        # Assuming there are no other team_images in the database, this
        # specifies that the TeamImage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TeamImage.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => team_image.to_param, :team_image => { "these" => "params" }}, valid_session
      end

      it "assigns the requested team_image as @team_image" do
        team_image = TeamImage.create! valid_attributes
        put :update, {:id => team_image.to_param, :team_image => valid_attributes}, valid_session
        assigns(:team_image).should eq(team_image)
      end

      it "redirects to the team_image" do
        team_image = TeamImage.create! valid_attributes
        put :update, {:id => team_image.to_param, :team_image => valid_attributes}, valid_session
        response.should redirect_to(team_image)
      end
    end

    describe "with invalid params" do
      it "assigns the team_image as @team_image" do
        team_image = TeamImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeamImage.any_instance.stub(:save).and_return(false)
        put :update, {:id => team_image.to_param, :team_image => {  }}, valid_session
        assigns(:team_image).should eq(team_image)
      end

      it "re-renders the 'edit' template" do
        team_image = TeamImage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TeamImage.any_instance.stub(:save).and_return(false)
        put :update, {:id => team_image.to_param, :team_image => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested team_image" do
      team_image = TeamImage.create! valid_attributes
      expect {
        delete :destroy, {:id => team_image.to_param}, valid_session
      }.to change(TeamImage, :count).by(-1)
    end

    it "redirects to the team_images list" do
      team_image = TeamImage.create! valid_attributes
      delete :destroy, {:id => team_image.to_param}, valid_session
      response.should redirect_to(team_images_url)
    end
  end

end
